{"name": "Test login attempt with wrong credentials", "status": "passed", "steps": [{"name": "test_login_incorrect", "status": "passed", "attachments": [{"name": "screen", "source": "a0d5302e-8a60-42ed-8eba-5f27e428cfdb-attachment.png", "type": "image/png"}], "parameters": [{"name": "login_data", "value": "('', '')"}, {"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"9eba9319df73f71031c63af4d054cdd8\")>"}], "start": 1537454599698, "stop": 1537454616172}], "parameters": [{"name": "login_data", "value": "('', '')"}], "start": 1537454599697, "stop": 1537454616172, "uuid": "08db03b7-9683-4142-8950-840fd1a28457", "historyId": "f4349e5ae2ba336cc5543edae9a81784", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data2]", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "UI"}, {"name": "feature", "value": "User management"}, {"name": "story", "value": "Login"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "2248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}