{"name": "Test login attempt with wrong credentials", "status": "passed", "parameters": [{"name": "login_data", "value": "('alex_art', '')"}], "start": 1537445354286, "stop": 1537445379829, "uuid": "a430d4ee-8369-4790-9c80-d593cfc08b8c", "historyId": "bd8dff7e7869c90b8607f44062ef975e", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data1]", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User management"}, {"name": "story", "value": "Login"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "14380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}