{"name": "Test login attempt with wrong credentials", "status": "broken", "statusDetails": {"message": "TypeError: __call__() got an unexpected keyword argument 'type'", "trace": "self = <src.tests.test_selenium.TestLogin object at 0x000001CA112C41D0>\nlogin_data = ('alex_art', '')\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"32aec9c6a7a1df1e8b0922b8f8b8044a\")>\n\n    @allure.step\n    @allure.tag('UI')\n    @allure.feature('User management')\n    @allure.story('Login')\n    @allure.title(\"Test login attempt with wrong credentials\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @pytest.mark.parametrize(\"login_data\", [(\"alex_art\", \"test\"),\n                                            (\"alex_art\", \"\"),\n                                            (\"\", \"\"),\n                                            (\"Alexander_Artemov\", \"test\")])\n    def test_login_incorrect(self, login_data, driver):\n        login_page = LoginPage(driver)\n        login_page.go(\"http://jira.hillel.it:8080/\")\n        login_page.login(*login_data)\n    \n>       allure.attach('screenshot', driver.get_screenshot_as_png(), type=AttachmentType.PNG)\nE       TypeError: __call__() got an unexpected keyword argument 'type'\n\nsrc\\tests\\test_selenium.py:61: TypeError"}, "steps": [{"name": "test_login_incorrect", "status": "broken", "statusDetails": {"message": "TypeError: __call__() got an unexpected keyword argument 'type'\n", "trace": "  File \"c:\\users\\aartemov\\pycharmprojects\\pythoncourse\\phase4\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 141, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\aartemov\\PycharmProjects\\pythoncourse\\phase5\\src\\tests\\test_selenium.py\", line 61, in test_login_incorrect\n    allure.attach('screenshot', driver.get_screenshot_as_png(), type=AttachmentType.PNG)\n"}, "parameters": [{"name": "login_data", "value": "('alex_art', '')"}, {"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"32aec9c6a7a1df1e8b0922b8f8b8044a\")>"}], "start": 1537454322548, "stop": 1537454338819}], "parameters": [{"name": "login_data", "value": "('alex_art', '')"}], "start": 1537454322548, "stop": 1537454338820, "uuid": "42f28b81-71c1-4609-b904-781ea6725101", "historyId": "bd8dff7e7869c90b8607f44062ef975e", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data1]", "labels": [{"name": "feature", "value": "User management"}, {"name": "tag", "value": "UI"}, {"name": "story", "value": "Login"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "12392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}