{"name": "Test login attempt with wrong credentials", "status": "broken", "statusDetails": {"message": "TypeError: __call__() got an unexpected keyword argument 'type'", "trace": "self = <src.tests.test_selenium.TestLogin object at 0x000001CA103935C0>\nlogin_data = ('alex_art', 'test')\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"314f4602d31e800142e90d02816d9b41\")>\n\n    @allure.step\n    @allure.tag('UI')\n    @allure.feature('User management')\n    @allure.story('Login')\n    @allure.title(\"Test login attempt with wrong credentials\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @pytest.mark.parametrize(\"login_data\", [(\"alex_art\", \"test\"),\n                                            (\"alex_art\", \"\"),\n                                            (\"\", \"\"),\n                                            (\"Alexander_Artemov\", \"test\")])\n    def test_login_incorrect(self, login_data, driver):\n        login_page = LoginPage(driver)\n        login_page.go(\"http://jira.hillel.it:8080/\")\n        login_page.login(*login_data)\n    \n>       allure.attach('screenshot', driver.get_screenshot_as_png(), type=AttachmentType.PNG)\nE       TypeError: __call__() got an unexpected keyword argument 'type'\n\nsrc\\tests\\test_selenium.py:61: TypeError"}, "steps": [{"name": "test_login_incorrect", "status": "broken", "statusDetails": {"message": "TypeError: __call__() got an unexpected keyword argument 'type'\n", "trace": "  File \"c:\\users\\aartemov\\pycharmprojects\\pythoncourse\\phase4\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 141, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\aartemov\\PycharmProjects\\pythoncourse\\phase5\\src\\tests\\test_selenium.py\", line 61, in test_login_incorrect\n    allure.attach('screenshot', driver.get_screenshot_as_png(), type=AttachmentType.PNG)\n"}, "parameters": [{"name": "login_data", "value": "('alex_art', 'test')"}, {"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"314f4602d31e800142e90d02816d9b41\")>"}], "start": 1537454298618, "stop": 1537454316594}], "parameters": [{"name": "login_data", "value": "('alex_art', 'test')"}], "start": 1537454298617, "stop": 1537454316596, "uuid": "85c1d863-69eb-44cf-9629-de14d78f78c8", "historyId": "eb21a96018a81d1b7c1af44bc9928f0c", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data0]", "labels": [{"name": "feature", "value": "User management"}, {"name": "tag", "value": "UI"}, {"name": "story", "value": "Login"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "12392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}