{"name": "Test login attempt with wrong credentials", "status": "passed", "steps": [{"name": "test_login_incorrect", "status": "passed", "attachments": [{"name": "screen", "source": "d77a42eb-6bb4-4ece-bae7-757409ef25e6-attachment.png", "type": "image/png"}], "parameters": [{"name": "login_data", "value": "('Alexander_Artemov', 'test')"}, {"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"3c28bef5a7e389718faf830aa4196999\")>"}], "start": 1537515553999, "stop": 1537515570443}], "parameters": [{"name": "login_data", "value": "('Alexander_Artemov', 'test')"}], "start": 1537515553999, "stop": 1537515570443, "uuid": "2e34af7f-4554-4966-920b-20de5b23df9a", "historyId": "384da9776e08e2dbe65b4e7101c5fe29", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data3]", "labels": [{"name": "feature", "value": "User management"}, {"name": "severity", "value": "normal"}, {"name": "tag", "value": "UI"}, {"name": "story", "value": "Login"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "20216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}