{"name": "Test login attempt with wrong credentials", "status": "passed", "steps": [{"name": "test_login_incorrect", "status": "passed", "parameters": [{"name": "login_data", "value": "('Alexander_Artemov', 'test')"}, {"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"ef4d4cb63728948e8cd5dcf7c65a3273\")>"}], "start": 1537449236984, "stop": 1537449256162}], "parameters": [{"name": "login_data", "value": "('Alexander_Artemov', 'test')"}], "start": 1537449236984, "stop": 1537449256162, "uuid": "bc889209-1070-4ccd-a8ba-92d217cbf534", "historyId": "384da9776e08e2dbe65b4e7101c5fe29", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data3]", "labels": [{"name": "story", "value": "Login"}, {"name": "tag", "value": "UI"}, {"name": "feature", "value": "User management"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "21332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}