{"name": "Test login attempt with wrong credentials", "status": "passed", "steps": [{"name": "test_login_incorrect", "status": "passed", "parameters": [{"name": "login_data", "value": "('', '')"}, {"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"196b3e6c1e1a8ab3e62c3b02e10b827a\")>"}], "start": 1537449215259, "stop": 1537449231982}], "parameters": [{"name": "login_data", "value": "('', '')"}], "start": 1537449215258, "stop": 1537449231983, "uuid": "3776e9ed-2ff1-4c4c-93ef-51273bb1a726", "historyId": "f4349e5ae2ba336cc5543edae9a81784", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data2]", "labels": [{"name": "story", "value": "Login"}, {"name": "tag", "value": "UI"}, {"name": "feature", "value": "User management"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "21332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}